# Introduction of Numpy

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [2]:
#!pip install numpy

import numpy as np

## Numpy Arrays

In [2]:
type(np.array(["vbhvh", 2, 3]))

numpy.ndarray

In [3]:
#Convert a list into an array
list_1=[1,2,3,4]

array_1=np.array(list_1)
array_1

array([1, 2, 3, 4])

In [4]:
#Upcasting:
np.array([1, 2, 3.6])

array([1. , 2. , 3.6])

In [5]:
#two dimension
list_2=[7,8,9,10]
list_combo=[list_1,list_2]
ar2=np.array(list_combo)
ar2

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [6]:
ar2.shape

(2, 4)

In [7]:
ar2.sum()

44

In [8]:
ar2.max()

10

In [9]:
ar2.min()

1

In [10]:
ar2.mean()

5.5

In [11]:
#dtype
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [12]:
#Creating an array from sub-classes:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [13]:
# How to create create a record array from a (flat) list of arrays
x1=np.array([1,2,3,4])
x2=np.array(['pen','pencil','paper','rubber'])
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])

In [14]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'pen', 1.1, 1.1), (2, 'pencil', 2. , 2. ),
           (3, 'paper', 3. , 3. ), (4, 'rubber', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U6'), ('c', '<f8'), ('d', '<f8')])

## Arange and Reshaping

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#Number spaced apart by 2.3
np.arange(5,16,2.3)# A series of numbers from low to high

array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [17]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [18]:
np.arange(0,50).reshape((5,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

## Random number generation

In [19]:
from numpy.random import randint as ri
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))


Vector of random integers
 -------------------------------------------------- 
 [61 92  3 99 31 62 60 58 78 33]

Here is the sorted vector
 -------------------------------------------------- 
 [ 3 31 33 58 60 61 62 78 92 99]


In [20]:
print("Random number generation (from Uniform distribution)")
# 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary
print(np.random.rand(2,3))

Random number generation (from Uniform distribution)
[[0.40798798 0.62459862 0.18090497]
 [0.34358373 0.98777972 0.42281458]]


In [21]:
#randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print(np.random.randint(1,100,(4,4))) 
# 20 samples drawn from a dice throw
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20))

[[ 3 38 15  4]
 [90 20 67 11]
 [92 13 41 71]
 [29 86 85 59]]

20 samples drawn from a dice throw: [3 3 6 1 4 1 2 2 3 5 4 4 3 5 6 5 4 5 6 1]


## Indexing and Slicing

In [22]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr[7]

7

In [24]:
arr[3:6:2]

array([3, 5])

In [25]:
arr[:4]

array([0, 1, 2, 3])

In [26]:
#3 Elements from last backwards
arr[-1:7:-1]

array([10,  9,  8])

In [27]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [2 4 9]


In [28]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr[3:6]

array([3, 4, 5])

## Indexing multi dimensional array

In [30]:
array_2d=np.array(([3,4,5],[6,7,8],[9,10,11]))
array_2d

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
#array_2d[row_num][col_num]
array_2d[1][1]

7

In [32]:
array_2d[0]

array([3, 4, 5])

# Matrix Creation

In [3]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [4]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [6]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples

Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [7]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


## Array Functions

In [33]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)


1st Matrix of random single-digit numbers

 [[7 7 1]
 [7 7 4]
 [7 3 9]]


In [34]:
#sqare root
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


Sq-root of 1st matrix using np
------------------
 [[2.64575131 2.64575131 1.        ]
 [2.64575131 2.64575131 2.        ]
 [2.64575131 1.73205081 3.        ]]


In [35]:
#Exponential
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[1.09663316e+03 1.09663316e+03 2.71828183e+00]
 [1.09663316e+03 1.09663316e+03 5.45981500e+01]
 [1.09663316e+03 2.00855369e+01 8.10308393e+03]]


In [36]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.84509804 0.84509804 0.        ]
 [0.84509804 0.84509804 0.60205999]
 [0.84509804 0.47712125 0.95424251]]
[[7 7 1]
 [7 7 4]
 [7 3 9]]


In [37]:
mat1.mean()

5.777777777777778